### ISSUE TITLE
Cli tool for Golte

### ISSUE THREAD

**Issue by TimLai666** [nichady/golte#14]
Hey there! I made a cli tool for Golte.
https://github.com/TimLai666/golte-cli

With this tool, you can:
- create a Golte project, automatically run `npm init`, `go mod init`, etc.
- build a Golte project.
- run a Golte project.

**Comment by nichady** [comment]
Awesome! I've added your project to the README (03c65fc69e028aa43d16a145ba1875a6d207bd7b).
