### ISSUE TITLE
A more detailed documentation

### ISSUE THREAD

**Issue by gevera** [nichady/golte#2]
it seems right now  Golte doesnt work well with Echo. 

```go

package main

import (
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/nichady/golte"

	"gosvlt/build"
)

func main() {
	r := echo.New()

	r.Use(build.Golte)

	r.GET("/", golte.Page("routes/home"))
	r.GET("/ping", Pong)
	
	http.ListenAndServe(":7777", r)
}

func Pong(c echo.Context) error {
	return c.String(http.StatusOK, "pong")
}
```

And here are the errors

```bash
# command-line-arguments
./main.go:16:8: cannot use build.Golte (variable of type func(http.Handler) http.Handler) as echo.MiddlewareFunc value in argument to r.Use
./main.go:18:13: cannot use golte.Page("routes/home") (value of type http.HandlerFunc) as echo.HandlerFunc value in argument to r.GET
```

---------------

Not much familiar with Go (coming from Node.js world so Echo is looks like Express), it will be helpful if in the docs there would be a simple CRUD example with a list of items {#each ..} block,  a  form with a POST request that is being handled by Go backend.  Other then that, a pretty solid library. Oh, btw, does it handle websockets?

**Comment by nichady** [comment]
Golte uses the standard library signatures for handlers and middlewares. So handlers will be of type `http.HandlerFunc` and middlewares will be of type `func(http.Handler) http.Handler`. If you want to use them in echo, you would have to wrap them, as shown [here](https://github.com/nichady/golte/blob/0242f0210c5ee06ede03404276cf47324aa26b1b/_examples/routers/echo.go#L12).


Golte doesn't handle websockets.

I will add another example soon.
